name: Waka Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ===== Section 1 =====
      - name: WakaTime Basic Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka_basic

          SHOW_TIMEZONE=false 
          SHOW_PROJECTS=False
          SHOW_EDITORS=False
          SHOW_OS=False
          SHOW_LANGUAGE=False
          SHOW_LINES_OF_CODE=False
          SHOW_LOC_CHART=False
          SHOW_SHORT_INFO=False
          SHOW_UPDATED_DATE=False

      - name: WakaTime Full Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka_full

          SHOW_PROFILE_VIEWS: false
          SHOW_TOTAL_CODE_TIME: false
