name: Waka Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: WakaTime Basic Stats
        uses: circle-earth/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          SECTION_NAME: waka_basic

          SHOW_PROFILE_VIEWS: true
          SHOW_CODE_TIME: true

          SHOW_LINES_OF_CODE: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_LANGUAGE: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_COMMIT: false

      - name: WakaTime Full Stats
        uses: circle-earth/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          SECTION_NAME: waka_full

          SHOW_PROFILE_VIEWS: false
          SHOW_CODE_TIME: false

          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
          SHOW_COMMIT: true
