name: Waka Readme Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: WakaTime Basic Stats
        uses: circle-earth/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka_basic

          SHOW_LANGUAGE: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_COMMIT: false
          SHOW_TIMEZONE: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_LANGUAGE_PER_REPO: false

      - name: WakaTime Full Stats
        uses: circle-earth/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka_full

          SHOW_PROFILE_VIEWS: false
          SHOW_TOTAL_CODE_TIME: false
